-- CBS File Generator Database Schema

-- Sequences
CREATE SEQUENCE IF_APP_CONFIG_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE IF_DB_TOKEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE IF_FILE_GEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- IF_APP_CONFIG Table - Registry for application configuration
CREATE TABLE IF_APP_CONFIG (
    CONFIG_ID NUMBER NOT NULL,
    CONFIG_KEY VARCHAR2(100) NOT NULL,
    CONFIG_VALUE CLOB NOT NULL,
    CONFIG_TYPE VARCHAR2(20),
    DESCRIPTION CLOB,
    ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    UPDATED_DATE TIMESTAMP,
    CONSTRAINT PK_IF_APP_CONFIG PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UQ_IF_CONFIG_KEY UNIQUE (CONFIG_KEY)
);

CREATE INDEX IDX_IF_APP_CONFIG_TYPE ON IF_APP_CONFIG(CONFIG_TYPE);
CREATE INDEX IDX_IF_APP_CONFIG_ACTIVE ON IF_APP_CONFIG(ACTIVE);

-- IF_DB_TOKEN Table - Token-based authentication
CREATE TABLE IF_DB_TOKEN (
    TOKEN_ID NUMBER NOT NULL,
    TOKEN_VALUE VARCHAR2(500) NOT NULL,
    APPLICATION_NAME VARCHAR2(100) NOT NULL,
    ISSUED_BY VARCHAR2(50),
    ISSUED_DATE TIMESTAMP DEFAULT SYSDATE,
    EXPIRY_DATE TIMESTAMP,
    ACTIVE NUMBER(1) DEFAULT 1,
    LAST_USED_DATE TIMESTAMP,
    CONSTRAINT PK_IF_DB_TOKEN PRIMARY KEY (TOKEN_ID),
    CONSTRAINT UQ_IF_TOKEN_VALUE UNIQUE (TOKEN_VALUE)
);

CREATE INDEX IDX_IF_DB_TOKEN_ACTIVE ON IF_DB_TOKEN(ACTIVE);
CREATE INDEX IDX_IF_DB_TOKEN_APP_NAME ON IF_DB_TOKEN(APPLICATION_NAME);
CREATE INDEX IDX_IF_DB_TOKEN_VAL_ACT ON IF_DB_TOKEN(TOKEN_VALUE, ACTIVE);

-- IF_FILE_GENERATION Table - Track file generation jobs
CREATE TABLE IF_FILE_GENERATION (
    FILE_GEN_ID NOT NULL,
    JOB_ID VARCHAR2(100) NOT NULL,
    INTERFACE_TYPE VARCHAR2(100) NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    RECORD_COUNT NUMBER DEFAULT 0,
    SKIPPED_RECORD_COUNT NUMBER DEFAULT 0,
    INVALID_RECORD_COUNT NUMBER DEFAULT 0,
    ERROR_MESSAGE CLOB,
    CREATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMPLETED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_IF_FILE_GENERATION PRIMARY KEY (FILE_GEN_ID),
    CONSTRAINT UQ_JOB_ID UNIQUE (JOB_ID),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('PENDING','PROCESSING','STOPPED','FINALIZING','COMPLETED','FAILED'))
);

CREATE INDEX IDX_IF_FILE_GEN_STATUS ON IF_FILE_GENERATION(STATUS);
CREATE INDEX IDX_IF_FILE_GEN_TYPE_STATUS ON IF_FILE_GENERATION(INTERFACE_TYPE, STATUS);
CREATE INDEX IDX_IF_FILE_GEN_TYPE_DATE ON IF_FILE_GENERATION(INTERFACE_TYPE, CREATED_DATE DESC);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_DATE ON IF_FILE_GENERATION(CREATED_DATE);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_BY ON IF_FILE_GENERATION(CREATED_BY);

COMMIT;
