-- ===============================================================
-- CBS File Generator - Core Application Tables (PostgreSQL)
-- ===============================================================

-- Registry for application configuration
CREATE TABLE IF_APP_CONFIG (
    CONFIG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONFIG_KEY VARCHAR(100) NOT NULL,
    CONFIG_VALUE TEXT NOT NULL,
    CONFIG_TYPE VARCHAR(20),
    DESCRIPTION TEXT,
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP,
    CONSTRAINT UQ_IF_APP_CONFIG_KEY UNIQUE (CONFIG_KEY)
);

CREATE INDEX IDX_IF_APP_CONFIG_TYPE ON IF_APP_CONFIG(CONFIG_TYPE);
CREATE INDEX IDX_IF_APP_CONFIG_ACTIVE ON IF_APP_CONFIG(ACTIVE);

-- Token-based authentication
CREATE TABLE IF_DB_TOKEN (
    TOKEN_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOKEN_VALUE VARCHAR(500) NOT NULL,
    APPLICATION_NAME VARCHAR(100) NOT NULL,
    ISSUED_BY VARCHAR(50),
    ISSUED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRY_DATE TIMESTAMP,
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    LAST_USED_DATE TIMESTAMP,
    CONSTRAINT UQ_IF_TOKEN_VALUE UNIQUE (TOKEN_VALUE)
);

CREATE INDEX IDX_IF_DB_TOKEN_ACTIVE ON IF_DB_TOKEN(ACTIVE);
CREATE INDEX IDX_IF_DB_TOKEN_APP_NAME ON IF_DB_TOKEN(APPLICATION_NAME);
CREATE INDEX IDX_IF_DB_TOKEN_VAL_ACT ON IF_DB_TOKEN(TOKEN_VALUE, ACTIVE);

-- Track file generation jobs
CREATE TABLE IF_FILE_GENERATION (
    FILE_GEN_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID VARCHAR(100) NOT NULL,
    INTERFACE_TYPE VARCHAR(100) NOT NULL,
    FILE_NAME TEXT NOT NULL,
    FILE_PATH TEXT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    RECORD_COUNT BIGINT DEFAULT 0,
    SKIPPED_RECORD_COUNT BIGINT DEFAULT 0,
    INVALID_RECORD_COUNT BIGINT DEFAULT 0,
    ERROR_MESSAGE TEXT,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_DATE TIMESTAMP,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT UQ_IF_FILE_GENERATION_JOB_ID UNIQUE (JOB_ID),
    CONSTRAINT CHK_IF_FILE_GEN_STATUS CHECK (STATUS IN ('PENDING','QUEUED','PROCESSING','STOPPED','FINALIZING','COMPLETED','FAILED'))
);

CREATE INDEX IDX_IF_FILE_GEN_STATUS ON IF_FILE_GENERATION(STATUS);
CREATE INDEX IDX_IF_FILE_GEN_TYPE_DATE ON IF_FILE_GENERATION(INTERFACE_TYPE, CREATED_DATE DESC);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_DATE ON IF_FILE_GENERATION(CREATED_DATE);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_BY ON IF_FILE_GENERATION(CREATED_BY);

-- Guard: Prevent multiple PENDING/PROCESSING jobs for the same interface
CREATE UNIQUE INDEX UQ_IF_FILE_GEN_ACTIVE
ON IF_FILE_GENERATION (INTERFACE_TYPE)
WHERE STATUS IN ('PENDING', 'QUEUED', 'PROCESSING');

-- ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID BIGSERIAL PRIMARY KEY,
    ORDER_NUMBER VARCHAR(100) NOT NULL,
    ORDER_AMOUNT NUMERIC(18,2),
    ORDER_DATE TIMESTAMP,
    CUSTOMER_ID VARCHAR(50),
    CUSTOMER_NAME VARCHAR(200),
    STATUS VARCHAR(20),
    CONSTRAINT UQ_ORDERS_ORDER_NUMBER UNIQUE (ORDER_NUMBER)
);

-- INDEXES FOR ORDERS TABLE
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS(CUSTOMER_ID);

-- LINE_ITEMS TABLE
CREATE TABLE LINE_ITEMS (
    LINE_ITEM_ID VARCHAR(50) PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID VARCHAR(50),
    PRODUCT_NAME VARCHAR(200),
    QUANTITY INTEGER,
    UNIT_PRICE NUMERIC(18,2),
    LINE_AMOUNT NUMERIC(18,2),
    STATUS VARCHAR(20),
    CONSTRAINT FK_LINE_ITEMS_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE
);

-- INDEXES FOR LINE_ITEMS TABLE
CREATE INDEX IDX_LINE_ITEMS_ORDER_ID ON LINE_ITEMS(ORDER_ID);
CREATE INDEX IDX_LINE_ITEMS_STATUS ON LINE_ITEMS(STATUS);
CREATE INDEX IDX_LINE_ITEMS_PRODUCT_ID ON LINE_ITEMS(PRODUCT_ID);

COMMIT;
