-- ===============================================================
-- CBS File Generator - Core Application Tables (Oracle)
-- ===============================================================

-- Registry for application configuration
CREATE TABLE IF_APP_CONFIG (
    CONFIG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONFIG_KEY VARCHAR2(100) NOT NULL,
    CONFIG_VALUE CLOB NOT NULL,
    CONFIG_TYPE VARCHAR2(20),
    DESCRIPTION CLOB,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP,
    CONSTRAINT UQ_IF_APP_CONFIG_KEY UNIQUE (CONFIG_KEY)
);

CREATE INDEX IDX_IF_APP_CONFIG_TYPE ON IF_APP_CONFIG(CONFIG_TYPE);
CREATE INDEX IDX_IF_APP_CONFIG_ACTIVE ON IF_APP_CONFIG(ACTIVE);

-- Token-based authentication
CREATE TABLE IF_DB_TOKEN (
    TOKEN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOKEN_VALUE VARCHAR2(500) NOT NULL,
    APPLICATION_NAME VARCHAR2(100) NOT NULL,
    ISSUED_BY VARCHAR2(50),
    ISSUED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRY_DATE TIMESTAMP,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    LAST_USED_DATE TIMESTAMP,
    CONSTRAINT UQ_IF_TOKEN_VALUE UNIQUE (TOKEN_VALUE)
);

CREATE INDEX IDX_IF_DB_TOKEN_ACTIVE ON IF_DB_TOKEN(ACTIVE);
CREATE INDEX IDX_IF_DB_TOKEN_APP_NAME ON IF_DB_TOKEN(APPLICATION_NAME);
CREATE INDEX IDX_IF_DB_TOKEN_VAL_ACT ON IF_DB_TOKEN(TOKEN_VALUE, ACTIVE);

-- Track file generation jobs
CREATE TABLE IF_FILE_GENERATION (
    FILE_GEN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID VARCHAR2(100) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(100),
    INTERFACE_TYPE VARCHAR2(100) NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    RECORD_COUNT NUMBER(12) DEFAULT 0,
    SKIPPED_RECORD_COUNT NUMBER(12) DEFAULT 0,
    INVALID_RECORD_COUNT NUMBER(12) DEFAULT 0,
    ERROR_MESSAGE CLOB,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT UQ_IF_FILE_GENERATION_JOB_ID UNIQUE (JOB_ID),
    CONSTRAINT UQ_IF_FILE_GEN_IDEM_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CHK_IF_FILE_GEN_STATUS CHECK (STATUS IN ('PENDING','QUEUED','PROCESSING','STOPPED','FINALIZING','COMPLETED','FAILED'))
);

CREATE INDEX IDX_IF_FILE_GEN_STATUS ON IF_FILE_GENERATION(STATUS);
CREATE INDEX IDX_IF_FILE_GEN_TYPE_DATE ON IF_FILE_GENERATION(INTERFACE_TYPE, CREATED_DATE DESC);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_DATE ON IF_FILE_GENERATION(CREATED_DATE);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_BY ON IF_FILE_GENERATION(CREATED_BY);

-- Guard: Prevent multiple PENDING/PROCESSING jobs for the same interface
CREATE UNIQUE INDEX UQ_IF_FILE_GEN_ACTIVE
ON IF_FILE_GENERATION (
    INTERFACE_TYPE,
    CASE
        WHEN STATUS IN ('PENDING', 'QUEUED', 'PROCESSING')
        THEN STATUS
        ELSE NULL
    END
);

CREATE TABLE IF_FILE_GENERATION_AUDIT (
    AUDIT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID VARCHAR2(100),
    OLD_STATUS VARCHAR2(50),
    NEW_STATUS VARCHAR2(50),
    CHANGED_BY VARCHAR2(100),
    CHANGED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    REASON VARCHAR2(500)
);

CREATE INDEX IDX_IF_FILE_GEN_AUDIT_JOB_ID ON IF_FILE_GENERATION_AUDIT (JOB_ID, CHANGED_DATE);

-- ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_NUMBER VARCHAR2(100) NOT NULL,
    ORDER_AMOUNT NUMBER(18,2),
    ORDER_DATE TIMESTAMP,
    CUSTOMER_ID VARCHAR2(50),
    CUSTOMER_NAME VARCHAR2(200),
    STATUS VARCHAR2(20),
    CONSTRAINT UQ_ORDERS_ORDER_NUMBER UNIQUE (ORDER_NUMBER)
);

-- Indexes for ORDERS table
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS(CUSTOMER_ID);

-- LINE_ITEMS table
CREATE TABLE LINE_ITEMS (
    LINE_ITEM_ID VARCHAR2(50) PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID VARCHAR2(50),
    PRODUCT_NAME VARCHAR2(200),
    QUANTITY NUMBER(10),
    UNIT_PRICE NUMBER(18,2),
    LINE_AMOUNT NUMBER(18,2),
    STATUS VARCHAR2(20),
    CONSTRAINT FK_LINE_ITEMS_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE
);

-- Indexes for LINE_ITEMS table
CREATE INDEX IDX_LINE_ITEMS_ORDER_ID ON LINE_ITEMS(ORDER_ID);
CREATE INDEX IDX_LINE_ITEMS_STATUS ON LINE_ITEMS(STATUS);
CREATE INDEX IDX_LINE_ITEMS_PRODUCT_ID ON LINE_ITEMS(PRODUCT_ID);

COMMIT;
