-- ===============================================================
-- CBS File Generator - Core Application Tables (Oracle)
-- ===============================================================

-- Sequences
CREATE SEQUENCE IF_APP_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF_DB_TOKEN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF_FILE_GEN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Registry for application configuration
CREATE TABLE IF_APP_CONFIG (
    CONFIG_ID NUMBER NOT NULL,
    CONFIG_KEY VARCHAR2(100) NOT NULL,
    CONFIG_VALUE CLOB NOT NULL,
    CONFIG_TYPE VARCHAR2(20),
    DESCRIPTION CLOB,
    ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    UPDATED_DATE TIMESTAMP,
    CONSTRAINT PK_IF_APP_CONFIG PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UQ_IF_CONFIG_KEY UNIQUE (CONFIG_KEY)
);

CREATE INDEX IDX_IF_APP_CONFIG_TYPE ON IF_APP_CONFIG(CONFIG_TYPE);
CREATE INDEX IDX_IF_APP_CONFIG_ACTIVE ON IF_APP_CONFIG(ACTIVE);

-- Token-based authentication
CREATE TABLE IF_DB_TOKEN (
    TOKEN_ID NUMBER NOT NULL,
    TOKEN_VALUE VARCHAR2(500) NOT NULL,
    APPLICATION_NAME VARCHAR2(100) NOT NULL,
    ISSUED_BY VARCHAR2(50),
    ISSUED_DATE TIMESTAMP DEFAULT SYSDATE,
    EXPIRY_DATE TIMESTAMP,
    ACTIVE NUMBER(1) DEFAULT 1,
    LAST_USED_DATE TIMESTAMP,
    CONSTRAINT PK_IF_DB_TOKEN PRIMARY KEY (TOKEN_ID),
    CONSTRAINT UQ_IF_TOKEN_VALUE UNIQUE (TOKEN_VALUE)
);

CREATE INDEX IDX_IF_DB_TOKEN_ACTIVE ON IF_DB_TOKEN(ACTIVE);
CREATE INDEX IDX_IF_DB_TOKEN_APP_NAME ON IF_DB_TOKEN(APPLICATION_NAME);
CREATE INDEX IDX_IF_DB_TOKEN_VAL_ACT ON IF_DB_TOKEN(TOKEN_VALUE, ACTIVE);

-- Track file generation jobs
CREATE TABLE IF_FILE_GENERATION (
    FILE_GEN_ID NUMBER NOT NULL,
    JOB_ID VARCHAR2(100) NOT NULL,
    INTERFACE_TYPE VARCHAR2(100) NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    RECORD_COUNT NUMBER DEFAULT 0,
    SKIPPED_RECORD_COUNT NUMBER DEFAULT 0,
    INVALID_RECORD_COUNT NUMBER DEFAULT 0,
    ERROR_MESSAGE CLOB,
    CREATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMPLETED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_IF_FILE_GENERATION PRIMARY KEY (FILE_GEN_ID),
    CONSTRAINT UQ_JOB_ID UNIQUE (JOB_ID),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('PENDING','PROCESSING','STOPPED','FINALIZING','COMPLETED','FAILED'))
);

CREATE INDEX IDX_IF_FILE_GEN_STATUS ON IF_FILE_GENERATION(STATUS);
CREATE INDEX IDX_IF_FILE_GEN_TYPE_DATE ON IF_FILE_GENERATION(INTERFACE_TYPE, CREATED_DATE DESC);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_DATE ON IF_FILE_GENERATION(CREATED_DATE);
CREATE INDEX IDX_IF_FILE_GEN_CREATED_BY ON IF_FILE_GENERATION(CREATED_BY);

-- Guard: Prevent multiple PENDING/PROCESSING jobs for the same interface
CREATE UNIQUE INDEX UQ_IF_FILE_GEN_ACTIVE
ON IF_FILE_GENERATION (
    INTERFACE_TYPE,
    CASE
        WHEN STATUS IN ('PENDING', 'PROCESSING')
        THEN STATUS
        ELSE NULL
    END
);

-- ===============================================================
-- Quartz Scheduler Tables (Official Oracle Script)
-- ===============================================================

CREATE TABLE QRTZ_JOB_DETAILS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    JOB_CLASS_NAME   VARCHAR2(250) NOT NULL,
    IS_DURABLE VARCHAR2(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR2(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR2(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
    JOB_DATA BLOB NULL,
    CONSTRAINT QRTZ_JOB_DETAILS_PK PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE QRTZ_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    NEXT_FIRE_TIME NUMBER(13) NULL,
    PREV_FIRE_TIME NUMBER(13) NULL,
    PRIORITY NUMBER(13) NULL,
    TRIGGER_STATE VARCHAR2(16) NOT NULL,
    TRIGGER_TYPE VARCHAR2(8) NOT NULL,
    START_TIME NUMBER(13) NOT NULL,
    END_TIME NUMBER(13) NULL,
    CALENDAR_NAME VARCHAR2(200) NULL,
    MISFIRE_INSTR NUMBER(2) NULL,
    JOB_DATA BLOB NULL,
    CONSTRAINT QRTZ_TRIGGERS_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    CONSTRAINT QRTZ_TRIGGER_TO_JOBS_FK FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
      REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    REPEAT_COUNT NUMBER(7) NOT NULL,
    REPEAT_INTERVAL NUMBER(12) NOT NULL,
    TIMES_TRIGGERED NUMBER(10) NOT NULL,
    CONSTRAINT QRTZ_SIMPLE_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    CONSTRAINT QRTZ_SIMPLE_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
	REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE QRTZ_CRON_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    TIME_ZONE_ID VARCHAR2(80),
    CONSTRAINT QRTZ_CRON_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    CONSTRAINT QRTZ_CRON_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
      REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE QRTZ_BLOB_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    CONSTRAINT QRTZ_BLOB_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    CONSTRAINT QRTZ_BLOB_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE QRTZ_CALENDARS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    CALENDAR_NAME  VARCHAR2(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    CONSTRAINT QRTZ_CALENDARS_PK PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
);

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_GROUP  VARCHAR2(200) NOT NULL,
    CONSTRAINT QRTZ_PAUSED_TRIG_GRPS_PK PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
);

CREATE TABLE QRTZ_FIRED_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    ENTRY_ID VARCHAR2(95) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    FIRED_TIME NUMBER(13) NOT NULL,
    SCHED_TIME NUMBER(13) NOT NULL,
	PRIORITY NUMBER(13) NOT NULL,
    STATE VARCHAR2(16) NOT NULL,
    JOB_NAME VARCHAR2(200) NULL,
    JOB_GROUP VARCHAR2(200) NULL,
    IS_NONCONCURRENT VARCHAR2(1) NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NULL,
    CONSTRAINT QRTZ_FIRED_TRIGGER_PK PRIMARY KEY (SCHED_NAME,ENTRY_ID)
);

CREATE TABLE QRTZ_SCHED_STATE (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(13) NOT NULL,
    CHECKIN_INTERVAL NUMBER(13) NOT NULL,
    CONSTRAINT QRTZ_SCHED_STATE_PK PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
);

CREATE TABLE QRTZ_LOCKS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    LOCK_NAME  VARCHAR2(40) NOT NULL,
    CONSTRAINT QRTZ_LOCKS_PK PRIMARY KEY (SCHED_NAME,LOCK_NAME)
);

-- ===============================================================
-- Spring Batch Metadata Tables (Standard Oracle Script)
-- ===============================================================

CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0) ,
	JOB_NAME VARCHAR2(100) NOT NULL,
	JOB_KEY VARCHAR2(32) NOT NULL,
	CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0) ,
	JOB_INSTANCE_ID NUMBER(19,0) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR2(10) ,
	EXIT_CODE VARCHAR2(2500) ,
	EXIT_MESSAGE VARCHAR2(2500) ,
	LAST_UPDATED TIMESTAMP,
	JOB_CONFIGURATION_LOCATION VARCHAR2(2500) NULL,
	CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
	REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

-- Optimization for Maintenance Tasklet
CREATE INDEX IDX_BATCH_JOB_EXEC_START ON BATCH_JOB_EXECUTION(START_TIME);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL ,
	TYPE_CD VARCHAR2(6) NOT NULL ,
	KEY_NAME VARCHAR2(100) NOT NULL ,
	STRING_VAL VARCHAR2(250) ,
	DATE_VAL TIMESTAMP DEFAULT NULL ,
	LONG_VAL NUMBER(19,0) ,
	DOUBLE_VAL NUMBER ,
	IDENTIFYING CHAR(1) NOT NULL ,
	CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0) NOT NULL,
	STEP_NAME VARCHAR2(100) NOT NULL,
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
	START_TIME TIMESTAMP NOT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR2(10) ,
	COMMIT_COUNT NUMBER(19,0) ,
	READ_COUNT NUMBER(19,0) ,
	FILTER_COUNT NUMBER(19,0) ,
	WRITE_COUNT NUMBER(19,0) ,
	READ_SKIP_COUNT NUMBER(19,0) ,
	WRITE_SKIP_COUNT NUMBER(19,0) ,
	PROCESS_SKIP_COUNT NUMBER(19,0) ,
	ROLLBACK_COUNT NUMBER(19,0) ,
	EXIT_CODE VARCHAR2(2500) ,
	EXIT_MESSAGE VARCHAR2(2500) ,
	LAST_UPDATED TIMESTAMP,
	CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

-- Optimization for Maintenance Tasklet
CREATE INDEX IDX_BATCH_STEP_EXEC_START ON BATCH_STEP_EXECUTION(START_TIME);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
	SERIALIZED_CONTEXT CLOB ,
	CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
	REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
	SERIALIZED_CONTEXT CLOB,
	CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

-- Sequences for Batch (Required for Oracle)
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 CACHE 20;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 CACHE 20;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 CACHE 20;

COMMIT;
